Update ci-cd.yml

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -128,6 +128,25 @@ jobs:
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
 
+      # ADDed OIDC
+      - name: Check OIDC and AWS role secret
+        env:
+          ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
+        run: |
+          if [ -z "$ACTIONS_ID_TOKEN_REQUEST_TOKEN" ]; then
+            echo "ERROR: GitHub OIDC token is not available"
+            exit 1
+          fi
+  
+          if [ -z "$ROLE_ARN" ]; then
+            echo "ERROR: AWS_ROLE_ARN secret is empty or unavailable"
+            exit 1
+          fi
+  
+          echo "GitHub OIDC token is available"
+          echo "AWS_ROLE_ARN secret is available"
+
+
       - name: Configure AWS credentials via OIDC
         uses: aws-actions/configure-aws-credentials@v6.2.3
         with:
